/**
 * Dati astronomici dei pianeti del sistema solare.
 * Distanze e velocità sono scalate per la visualizzazione.
 */
export const PLANETS = [
  {
    name: 'Mercurio',
    tag: 'PIANETA ROCCIOSO',
    R: 0.38,       // raggio scena
    dist: 14,      // distanza dal sole (unità scena)
    spd: 4.74,     // velocità orbitale relativa
    tilt: 0.034,   // inclinazione assiale (rad)
    textureKey: 'mercury',
    emi: 0x1a1a1a,
    emiI: 0.2,
    shin: 8,
    info: {
      dist: '57.9M km',
      period: '88 giorni',
      diam: '4,879 km',
      moons: '0',
      desc: 'Il pianeta più piccolo e più vicino al Sole. La sua superficie è coperta da crateri e le temperature oscillano tra −180°C e +430°C.',
    },
  },
  {
    name: 'Venere',
    tag: 'PIANETA GEMELLO',
    R: 0.95,
    dist: 21,
    spd: 3.5,
    tilt: 3.096,
    textureKey: 'venus',
    emi: 0x251800,
    emiI: 0.2,
    shin: 15,
    info: {
      dist: '108.2M km',
      period: '225 giorni',
      diam: '12,104 km',
      moons: '0',
      desc: "Il pianeta più caldo del sistema solare (462°C in media). Un'atmosfera densa di CO₂ crea un effetto serra estremo.",
    },
  },
  {
    name: 'Terra',
    tag: 'IL NOSTRO PIANETA',
    R: 1.0,
    dist: 29,
    spd: 2.98,
    tilt: 0.409,
    textureKey: 'earth',
    emi: 0x001530,
    emiI: 0.18,
    shin: 28,
    info: {
      dist: '149.6M km',
      period: '365 giorni',
      diam: '12,756 km',
      moons: '1',
      desc: "L'unico pianeta conosciuto ad ospitare la vita, con oceani liquidi, atmosfera ricca di ossigeno e una Luna che stabilizza l'asse terrestre.",
    },
  },
  {
    name: 'Marte',
    tag: 'PIANETA ROSSO',
    R: 0.53,
    dist: 40,
    spd: 2.41,
    tilt: 0.44,
    textureKey: 'mars',
    emi: 0x180000,
    emiI: 0.18,
    shin: 8,
    info: {
      dist: '227.9M km',
      period: '687 giorni',
      diam: '6,792 km',
      moons: '2',
      desc: 'Il pianeta rosso ospita Olympus Mons, il vulcano più alto del sistema solare (21 km). Ha una sottile atmosfera di CO₂.',
    },
  },
  {
    name: 'Giove',
    tag: 'GIGANTE GASSOSO',
    R: 3.5,
    dist: 63,
    spd: 1.31,
    tilt: 0.055,
    textureKey: 'jupiter',
    emi: 0x201000,
    emiI: 0.2,
    shin: 12,
    info: {
      dist: '778.5M km',
      period: '4.333 giorni',
      diam: '142,984 km',
      moons: '95',
      desc: 'Il più grande pianeta del sistema solare. La Grande Macchia Rossa è una tempesta anticiclonica attiva da almeno 350 anni.',
    },
  },
  {
    name: 'Saturno',
    tag: 'PIANETA CON ANELLI',
    R: 3.0,
    dist: 90,
    spd: 0.97,
    tilt: 0.466,
    textureKey: 'saturn',
    emi: 0x1c1000,
    emiI: 0.2,
    shin: 10,
    hasRings: true,
    info: {
      dist: '1.43 MLD km',
      period: '10.759 giorni',
      diam: '120,536 km',
      moons: '146',
      desc: "Il sistema di anelli di Saturno si estende per 282.000 km ma è spesso solo poche decine di metri. Densità media inferiore all'acqua.",
    },
  },
  {
    name: 'Urano',
    tag: 'GIGANTE DI GHIACCIO',
    R: 1.8,
    dist: 118,
    spd: 0.68,
    tilt: 1.706,
    textureKey: 'uranus',
    emi: 0x002030,
    emiI: 0.2,
    shin: 18,
    info: {
      dist: '2.87 MLD km',
      period: '30.687 giorni',
      diam: '51,118 km',
      moons: '28',
      desc: 'Urano ruota su un fianco (inclinazione assiale 98°), probabilmente a causa di un impatto cosmico antico. Ha 13 anelli sottili.',
    },
  },
  {
    name: 'Nettuno',
    tag: 'GIGANTE DI GHIACCIO',
    R: 1.7,
    dist: 147,
    spd: 0.54,
    tilt: 0.494,
    textureKey: 'neptune',
    emi: 0x000e35,
    emiI: 0.22,
    shin: 20,
    info: {
      dist: '4.50 MLD km',
      period: '60.190 giorni',
      diam: '49,528 km',
      moons: '16',
      desc: 'Il pianeta più lontano con venti che raggiungono 2.100 km/h. Il suo grande satellite Tritone orbita in senso retrogrado.',
    },
  },
];
